
target 'SoundHoleCoreTest-iOS' do
	platform :ios, '12.0'

	pod 'DataCpp', :git => 'git@github.com:lufinkey/data-cpp.git'
	pod 'AsyncCpp', :git => 'git@github.com:lufinkey/async-cpp.git'
	pod 'NodeMobile', :git => 'https://github.com/janeasystems/nodejs-mobile.git'
	pod 'NodeJSEmbed', :git => 'git@github.com:lufinkey/nodejs-embed.git'
end

target 'SoundHoleCoreTest-macOS' do
	platform :osx, '10.14'

	pod 'DataCpp', :git => 'git@github.com:lufinkey/data-cpp.git'
	pod 'AsyncCpp', :git => 'git@github.com:lufinkey/async-cpp.git'
	pod 'NodeJSEmbed', :git => 'git@github.com:lufinkey/nodejs-embed.git'
end
