
workspace 'SoundHoleCore'

def shared_pods
	pod 'DataCpp', :git => 'git@github.com:lufinkey/data-cpp.git'
	pod 'AsyncCpp', :git => 'git@github.com:lufinkey/async-cpp.git'
	pod 'IOCpp', :git => 'git@github.com:lufinkey/io-cpp.git'
	pod 'NodeJSEmbed', :git => 'git@github.com:lufinkey/nodejs-embed.git'
	pod 'sqlite3'
end

def shared_mobile_pods
	shared_pods
	pod 'NodeMobile', :git => 'https://github.com/janeasystems/nodejs-mobile.git'
end

target 'SoundHoleCore-iOS' do
	platform :ios, '13.0'
	shared_mobile_pods
end

target 'SoundHoleCoreTest-iOS' do
	platform :ios, '13.0'
	shared_mobile_pods
end

target 'SoundHoleCore-macOS' do
	platform :osx, '10.14'
	shared_pods
end

target 'SoundHoleCoreTest-macOS' do
	platform :osx, '10.14'
	shared_pods
end

post_install do |installer|
	installer.pods_project.targets.each do |target|
		if target.name == 'AsyncCpp-iOS' || target.name == 'AsyncCpp-macOS'
			target.build_configurations.each do |config|
				config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
				config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'FGL_DISPATCH_USES_MAIN=1'
			end
		end
	end
end

system("mkdir -p 'Pods'\n"\
	"cd Pods\n"\
	"if [ ! -e 'dtl/.git' ]; then\n"\
		"\tgit clone 'https://github.com/cubicdaiya/dtl'\n"\
	"fi\n")

