
workspace 'SoundHoleCore'

def shared_pods
	pod 'DataCpp', :git => 'git@github.com:lufinkey/data-cpp.git'
	pod 'AsyncCpp', :git => 'git@github.com:lufinkey/async-cpp.git'
	pod 'IOCpp', :git => 'git@github.com:lufinkey/io-cpp.git'
	pod 'NodeJSEmbed', :git => 'git@github.com:lufinkey/nodejs-embed.git'
	pod 'sqlite3'
end

def shared_mobile_pods
	shared_pods
	pod 'NodeMobile', :git => 'https://github.com/janeasystems/nodejs-mobile.git'
end

target 'SoundHoleCore-iOS' do
	platform :ios, '13.0'
	shared_mobile_pods
end

target 'SoundHoleCoreTest-iOS' do
	platform :ios, '13.0'
	shared_mobile_pods
end

target 'SoundHoleCore-macOS' do
	platform :osx, '10.14'
	shared_pods
end

target 'SoundHoleCoreTest-macOS' do
	platform :osx, '10.14'
	shared_pods
end

system("mkdir -p 'Pods'\n"\
	"cd Pods\n"\
	"if [ ! -e 'dtl/.git' ]; then\n"\
		"\tgit clone 'https://github.com/cubicdaiya/dtl'\n"\
	"else\n"\
		"\tcd dtl\n"\
		"\tgit pull\n"\
	"fi\n")
